# Run unit tests using CTest
name: Tests

on:
  push:
    branches: [ GSA-131-Testing-Document-Feedback-1 ]
  pull_request:
    branches: [ GSA-131-Testing-Document-Feedback-1 ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - name: changetosrc
       run: cd src && cd SCU_Main_Test && cmake && cd build && ctest