# Run unit tests using CTest
name: Tests

on:
  push:
    branches: [ GSA-131-Testing-Document-Feedback-1 ]
  pull_request:
    branches: [ GSA-131-Testing-Document-Feedback-1 ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
     - name: Check out repository code
       uses: actions/checkout@v2
    
     - name: Use Node.js
       uses: actions/setup-node@v2
    
     - name: Install dependencies
       run: npm ci
       working-directory: ./src/SCU_Main_Test

     - name: Run tests
       run: npm test
       working-directory: ./src/SCU_Main_Test