# Run unit tests using CTest
name: Tests

on:
  push:
    branches: [ GSA-131-Testing-Document-Feedback-1 ]
  pull_request:
    branches: [ GSA-131-Testing-Document-Feedback-1 ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
     - name: RunCtest
       run: ctest
       working-directory: ../src/SCU_Main_Test/build