# Run unit tests using CTest
name: Tests

on:
  push:
    branches: [ GSA-131-Testing-Document-Feedback-1 ]
  pull_request:
    branches: [ master ]

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run unit tests
      uses: HorstBaerbel/action-ctest@1.1
      # These are optional (defaults displayed)
      with:
        sourcedir: '../src/SCU_Main_Test'
        builddir: '../src/SCU_Main_Test/build'
        cmakeoptions: '--config Release'
        ctestoptions: 'CTest'